window_padding_width 15
background #151515
foreground #5d407e
url_color #E8E3E3
#black
color0 #151515
color8 #424242
#red
color1 #B66467
color9 #B66467
#green
color2 #774a8a
color10 #774a8a
#yellow
color3 #f15d66
color11 #f15d66
#blue
color4 #8696fd
color12 #5b6080
#magneta
color5 #A988B0
color13 #A988B0
#cyan
color6 #a0acfe
color14 #f764a1
#white
color7 #E8E3E3
color15 #E8E3E3




# BEGIN_KITTY_FONTS
font_family      family="Maple Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
