require("input")
require("monitors")
require("style")
require("keybinds")
require("windowrules")
hl.env("XCURSOR_THEME", "Quintom_Ink")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("GTK_THEME", "Adwaita-dark")
