## Video
profile=high-quality
hwdec=auto
## Behavior (personal preference)
keep-open=yes
save-position-on-quit

## Screenshots
screenshot-format=png
screenshot-dir="~/Pictures/mpv"
screenshot-template="%F-%p-%n"
screenshot-high-bit-depth=no

## Language Priority
slang=eng,en
alang=jpn,ja


osd-bar=no
osd-font-size=32


volume=80
volume-max=100
cursor-autohide=1000

