## Video
profile=high-quality
hwdec=nvdec
video-sync=display-desync
## Behavior (personal preference)
keep-open=yes
save-position-on-quit

## Screenshots
screenshot-format=png
screenshot-dir="~/Pictures/mpv"
screenshot-template="%F-%p-%n"
screenshot-high-bit-depth=no

## Language Priority
slang=eng,en
alang=jpn,ja


osd-bar=no
osd-font-size=32


volume=80
volume-max=100
cursor-autohide=1000

[Manga]
profile-desc="Read Manga"
profile-cond=filename and filename:match('%.cbz$') or filename:match('%.cbr$') or filename:match('%.zip$') or filename:match('%.rar$') ~= nil
profile=high-quality
dscale=mitchell
deband=no
